### PR TITLE
Couple minor changes

### PR DESCRIPTION
**Pull request by SuperWig**
- Changed std::random_shuffle to std::shuffle as [std::random_shuffle is deprecated in C++14](http://en.cppreference.com/w/cpp/algorithm/random_shuffle) 
- Previous change required writing a function to get the engine. I decided to make it return a reference as I figured that makes sense.
- Removed a line in the Cow tally that assigned '#' to the string which I thought was unnecessary
- I changed the PrintTurnSummary `BullCowCounts` to be a reference and PositiveExponentResult `Exponent` to not be one.

So in case you are unfamiliar, the general rule of thumb of whether to pass by value or to pass by reference is that if it's cheap to copy (true for all built in types like bool, char, int etc.) then probably wantto be passing by value unless you want to modify the value, like if you were to write a `ToLower` function for a string for example.

```
for(char& letter : word)
    letter = tolower(letter);
```

Otherwise it's probably best to pass by const ref or ref (depending whether you want to modify it)

### CODE REVIEW

**Comment by JackDraak** [comment]
My thought when using the signature `int32 FBullCowGame::PositiveExponentResult(int32 Base, const int32& Exponent)` was this: The function modifies Base with the constant Exponent so I pass a copy of Base [which is malleable] but only a reference to the [non-malleable] Exponent constant. Have I got something wrong or backwards with my logic?

The replacement for random_shuffle() I manually pulled-in, thank you for that!

**Comment by SuperWig** [comment]
For primitive types its better to pass by value as it should be better performance wise. Passing by reference would incur the cost of dereferencing a pointer and looking up it's address which would most likely be slower than just copying it's value. So unless you want to do something like the following you should be passing by value for the primitive types

```
void square(int& i) //obviously you won't be able to initialise a variable using this function
{
    i * i;
}
int main()
{
    int x = 5;
    square(x);
    int y = x; //y and x are 25
}
```

Also whilst double checking my facts, I learned that for passing by value the following are functionally equivalent:

```
foo(int x);
foo(const int x);
```

And the advice given by Herb Sutter (he has some good talks and works at Microsoft) was to use `foo(int x)` for the declaration in the header file and `foo(const int x)` in the implementation (if of course, you do actually want to make sure you don't modify the copy)

**Comment by JackDraak** [comment]
I certainly need a better understanding of what's going on under the hood, especially in regard to referencing, de-referencing and copying. Thanks for all the info. I've just pushed a new master where I believe I'm more appropriately using 'const' and '&'; in the latter case, only when referencing a string unless I missed something.

584322e6aa8fd6c3159ee9e4386e86f850b95c6d SHA of the new merge. Thanks again!

**Comment by SuperWig** [comment]
And this is where I feel like I'm horrifically bad at explaining things :P since those string functions should be passed by const & (unless of course you want to modify the data being passed in).

And yeah, this is quite a bit more advanced than what Ben has currently covered in the course and can be tricky to initially get your head around, especially when it's me tring to explain it :P.

**Comment by JackDraak** [comment]
ahh so you're saying I should have left lines 40, 49, 262, 278 as they were (FBullCowGame.cpp) and as well, 50, 72, 90, 91 in the header file? 76, 78 & 188 of Main.cpp too, even? Oi.. time to take a couple steps backward :)

**Comment by SuperWig** [comment]
Pretty much, though you shouldn't need to change line 78 in Main.cpp as that would be the function declaration and as I previously stated, you don't have to put const in a parameter type for a declaration if it's passing by value.

**Comment by JackDraak** [comment]
e9d6fef098552a07b63ee8764c3e12d21e411416

corrections corected, muchas gracias hombre!

**Comment by SuperWig** [comment]
Haha, no problem.

**Comment by SuperWig** [comment]
Though I feel like I might have made things more confusing than it is lol

**Comment by JackDraak** [comment]
Well I think I'm now clear on the shape of the change I just need to finish wrapping my mind around all the why's. Time to go back to some CS101 lectures and see if I can absorb more of the nitty-gritty around memory management, pointers, references, etc... now that I have some real-world experience using them.

**Pull request closed without merging**
