### PR TITLE
Moved the shuffle function to be kept in class

### PR DESCRIPTION
**Pull request by SuperWig**
So I originally created the getter for the engine as the std::shuffle algorithm required an engine, 
though I have a feeling it's not a good idea to do that but I just thought it would be easier to create a getter for the engine than to create a global scoped one for the one use case in main.cpp. 

What just occured to me last night was that the shuffle could just be moved to be in-class removing the need for either of those.

### CODE REVIEW

**Comment by JackDraak** [comment]
I'm torn; I like how the current example illustrates the use of the randomizer... Also to add the suggested function of allowing un-sorted cows would be a no-brainer in the current state because it's mimicking the other hint-toggle behaviours if it's used from Main.cpp... I'll have to ponder this one. Thanks for the suggestion, however!

**Comment by SuperWig** [comment]
Well in the mean time I'm going to crack open a book to see if it's actually a problem. It just (on my very limited knowledge on concurrency) that a getter for the mt19937 doesn't sound like it would be great for multiple threads.... But like I said... limited knowledge on that sort of stuff lol.

**Comment by SuperWig** [comment]
Well it didn't answer any questions I had unfortunately. However I would argue that the use of shuffling should be unknown to the interface and I still feel like the use of that specific generator should remain exclusive to that class and that if you really want to use shuffle in main.cpp that you should create a static global one for main.cpp.

**Comment by JackDraak** [comment]
Given the unknowns, I suppose the wise move is to merge this then; Implementing an option for unsorted output is a piece of cake either way :) Cheers!

**Pull request merged**
